### PR TITLE
Remove medium "Electronic Resource" from online resources.

### LINKED ISSUE #796: Adjust medium information for online resources
Reported by edoweb customer C.D. on 207-02-02 (referring to the Edoweb view):

> Bei Websites steht unter „Medium“ immer „Datenträger“ und
> „Online-Ressource“. Ich glaube, da ist was falsch rübergekommen. Diese
> Information speist sich, soviel ich weiß, aus dem Feld 050 in der
> Titelaufnahme. In diesem Feld *mit der Bezeichnung* „Datenträger“ steht
> an Pos. 8 ein „g“, was bedeutet "Elektronische Ressource(n) im
> Fernzugriff“ oder „Online-Resssource“. Aber angezeigt zu werden braucht
> nur „Online-Ressource“. „Datenträger“ wäre sogar irreführend. Könnten
> Sie es so einrichten, daß da nur „Online-Ressource“ steht?

See [current moprh, line 329](https://github.com/lobid/lodmill/blob/230e5e240ce6393c81c1851be5bcd2658b076c39/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L329) where `g` is indeed included in mapping to RDA carrier type "electonic resource" (http://rdaregistry.info/termList/RDACarrierType/1010"/). We should just remove it. 

From the MAB documentation:

```

050       DATENTRAEGER

          Indikator:
          blank = nicht definiert

          Datenelemente:
...

            8  Computerdatei
               a = nicht spezifiziert
               b = Diskette(n)
               c = Magnetbandkassette(n)
               d = Optische Speicherplatte(n)
                   (z.B. CD-ROM, CD-I, Photo-CD, WORM, DVD)
               e = Einsteckmodul(e)
               f = Magnetband, Magnetbaender
               g = Computerdatei(en) im Fernzugriff
               z = sonstige Computerdatei(en)
```

### PR DESCRIPTION
**Pull request by acka47**
Fixes #796. I don't know how the adjustment of test data works in this repo. @dr0i, please take over.

### CODE REVIEW

**Comment by dr0i** [comment]
We decided to no longer invest in this old repo. Also, the dependency to metafacture-core is no more working, even our hbz-metafacture clone is unusable.
Is this really needed?

**Comment by acka47** [comment]
Ok then, we will only change it in 2.0, won't fix here. Closing.

**Comment by dr0i** [comment]
Software rots like fish

**Comment by fsteeg** [comment]
> Also, the dependency to metafacture-core is no more working, even our hbz-metafacture clone is unusable.

I'm not arguing for fixing this or anything, but since the wording is getting a little drastic: it should work fine if we check out an older version of our metafacture fork, e.g. one of these: https://github.com/hbz/metafacture-core/releases

**Comment by jschnasse** [comment]
also consider that API 2.0 isn't released yet and we (hbz) will of course provide bug fixes for v1 and are able to handle dependecy issues on maintained software.

**Pull request closed without merging**
