### PR TITLE
Remove types bibo:Collection/Periodical & frbr:Manifestation.

### PR DESCRIPTION
**Pull request by acka47**
See #639 and hbz/lobid#164.

### CODE REVIEW

**Comment by dr0i** [comment]
@acka47 have a look if my commits are ok

**Comment by acka47** [comment]
@dr0i You commits look good. I added one more. Have a look.

**Comment by acka47** [comment]
I just saw that the DINI KIM working group "Titeldaten" recommens using `bibo:Periodical` for Zeitschriften and not `bibo:Journal`. Maybe we should accordingly in a next step replace Journal by Periodical. This shouldn't prevent us from merging this as `bibo:Periodical` for all ZDB resources as this is strictly wrong. Also, we use `bibo:Journal` for filtering in NWBib.

**Comment by dr0i** [comment]
Deployed test set to staging.

**Pull request merged**
